### ISSUE TITLE
AssertionError : assert len(new_pattern)==1 in modisco/aggregator.py

### ISSUE THREAD

**Issue by ofiryaish** [kundajelab/tfmodisco#89]
I tried to run TF-modisco on different subsets of data and got the following error for one of the subsets (other works fine):
```
Traceback (most recent call last):
  File "TF_modisco.py", line 207, in <module>
    main([model], data, "modisco/")
  File "TF_modisco.py", line 173, in main
    run_modisco(hyp_impscores=hyp_ex_list, impscores=ex_list, onehot_data=features, modisco_path=modisco_path)
  File "TF_modisco.py", line 67, in run_modisco
    **nulldist_args)
  File "/users/agnon/year2016/yaishof/.conda/envs/ofir_env/lib/python3.6/site-packages/modisco/tfmodisco_workflow/workflow.py", line 377, in __call__
    metacluster_seqlets)
  File "/users/agnon/year2016/yaishof/.conda/envs/ofir_env/lib/python3.6/site-packages/modisco/tfmodisco_workflow/seqlets_to_patterns.py", line 913, in __call__
    patterns=split_patterns) 
  File "/users/agnon/year2016/yaishof/.conda/envs/ofir_env/lib/python3.6/site-packages/modisco/aggregator.py", line 1007, in __call__
    assert len(new_pattern)==1
AssertionError
```

What can be the problem?

the full output:
[output.txt](https://github.com/kundajelab/tfmodisco/files/6210636/output.txt)

**Comment by AvantiShri** [comment]
Hi Ofir, which version of tfmodisco are you running?

Best,
Avanti

**Comment by ofiryaish** [comment]
@AvantiShri ,
I'm using modisco==0.5.9.0.

Thank you for your attention

**Comment by AvantiShri** [comment]
Hi, can you try the latest version (0.5.14)? I think this error should be fixed in that version.

Thanks,
Av
